from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.db import get_db
from app.services import dashboard_aggregator, ai_helper
from app.models.ai import AIQueryLog

router = APIRouter(prefix="/dashboard", tags=["dashboard"])


@router.get("/summary")
def dashboard_summary(db: Session = Depends(get_db)):
    summary = dashboard_aggregator.get_summary(db)
    # additive - if AI service is down, narrative degrades gracefully,
    # the numeric summary above is unaffected.
    summary["ai_narrative"] = ai_helper.generate_dashboard_narrative(summary)
    return summary


@router.post("/query")
def natural_language_query(query_text: str, user_id: int, db: Session = Depends(get_db)):
    """
    Lets management ask things like:
    'which projects are blocked due to pending approvals?'
    Currently answers using the numeric summary as context - can be extended
    to run structured DB queries generated by the LLM for deeper answers.
    """
    summary = dashboard_aggregator.get_summary(db)
    context_prompt = (
        f"Portfolio data: {summary}\n\nManagement question: {query_text}\n\n"
        "Answer concisely using only the data given."
    )
    response_text = ai_helper.generate_dashboard_narrative({"context": context_prompt})

    db.add(AIQueryLog(user_id=user_id, query_text=query_text, generated_response=response_text))
    db.commit()

    return {"query": query_text, "response": response_text}
